language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"

script:
  - echo "skipping tests"

install: true
deploy:
  provider: script
  script: cd docs/ && yarn install && yarn run deploy
  fqdn: hola.teatroautomovil.com
  email: carlosvega20@mail.com
  name: "carlosvega20"
  skip_cleanup: true
  on:
    branch: master